//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenueBookingSystem.Launcher.VenueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VenueSeatingDetails", Namespace="http://schemas.datacontract.org/2004/07/SmallVenueBookingSystem")]
    [System.SerializableAttribute()]
    public partial class VenueSeatingDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Booked_CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cust_AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Partially_EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Seat_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string booking_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isAvailableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Booked_Customer {
            get {
                return this.Booked_CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.Booked_CustomerField, value) != true)) {
                    this.Booked_CustomerField = value;
                    this.RaisePropertyChanged("Booked_Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cust_Age {
            get {
                return this.Cust_AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cust_AgeField, value) != true)) {
                    this.Cust_AgeField = value;
                    this.RaisePropertyChanged("Cust_Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partially_Enabled {
            get {
                return this.Partially_EnabledField;
            }
            set {
                if ((object.ReferenceEquals(this.Partially_EnabledField, value) != true)) {
                    this.Partially_EnabledField = value;
                    this.RaisePropertyChanged("Partially_Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seat_No {
            get {
                return this.Seat_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Seat_NoField, value) != true)) {
                    this.Seat_NoField = value;
                    this.RaisePropertyChanged("Seat_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string booking_date {
            get {
                return this.booking_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.booking_dateField, value) != true)) {
                    this.booking_dateField = value;
                    this.RaisePropertyChanged("booking_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isAvailable {
            get {
                return this.isAvailableField;
            }
            set {
                if ((this.isAvailableField.Equals(value) != true)) {
                    this.isAvailableField = value;
                    this.RaisePropertyChanged("isAvailable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VenueService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSeatingDetails", ReplyAction="http://tempuri.org/IService/GetSeatingDetailsResponse")]
        VenueBookingSystem.Launcher.VenueService.VenueSeatingDetails[] GetSeatingDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSeatingDetails", ReplyAction="http://tempuri.org/IService/GetSeatingDetailsResponse")]
        System.Threading.Tasks.Task<VenueBookingSystem.Launcher.VenueService.VenueSeatingDetails[]> GetSeatingDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BookVenueSeats", ReplyAction="http://tempuri.org/IService/BookVenueSeatsResponse")]
        string BookVenueSeats(string[] seats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BookVenueSeats", ReplyAction="http://tempuri.org/IService/BookVenueSeatsResponse")]
        System.Threading.Tasks.Task<string> BookVenueSeatsAsync(string[] seats);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : VenueBookingSystem.Launcher.VenueService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<VenueBookingSystem.Launcher.VenueService.IService>, VenueBookingSystem.Launcher.VenueService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VenueBookingSystem.Launcher.VenueService.VenueSeatingDetails[] GetSeatingDetails() {
            return base.Channel.GetSeatingDetails();
        }
        
        public System.Threading.Tasks.Task<VenueBookingSystem.Launcher.VenueService.VenueSeatingDetails[]> GetSeatingDetailsAsync() {
            return base.Channel.GetSeatingDetailsAsync();
        }
        
        public string BookVenueSeats(string[] seats) {
            return base.Channel.BookVenueSeats(seats);
        }
        
        public System.Threading.Tasks.Task<string> BookVenueSeatsAsync(string[] seats) {
            return base.Channel.BookVenueSeatsAsync(seats);
        }
    }
}
